name: Build and Publish

on:
  push:
    branches: 
      - main

jobs:
  # define job to build and publish docker image
  docker:
    name: Build Docker image and push to repository
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          # relative path to the place where source code with Dockerfile is located
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          # Note: tags has to be all lower-case
          tags: ghcr.io/hoellenwesen/docker-ark-dedicated-server:latest
          # build on feature branches, push only on master branch
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}